import mongoose from 'mongoose';
import { ContactMessage, Page, Project, Service, SiteSetting, Statistic } from '../models/content.js';
import { contactSchema, projectSchema, serviceSchema } from '../utils/validation.js';

const createSlug = (value) => String(value || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 140);
function resourceController(Model, schema, publicSort = '-createdAt') {
  return {
    async list(req, res, next) { try { const filter = req.user ? {} : { status: 'published' }; const data = await Model.find(filter).sort(publicSort); res.json({ success: true, data }); } catch (error) { next(error); } },
    async get(req, res, next) { try { const match = [{ slug: req.params.id }]; if (mongoose.Types.ObjectId.isValid(req.params.id)) match.unshift({ _id: req.params.id }); const query = req.user ? { $or: match } : { status: 'published', $or: match }; const item = await Model.findOne(query); if (!item) return res.status(404).json({ success: false, message: 'Content not found.' }); res.json({ success: true, data: item }); } catch (error) { next(error); } },
    async create(req, res, next) { try { const data = schema.parse(req.body); if (!data.slug) data.slug = createSlug(data.title); const item = await Model.create(data); res.status(201).json({ success: true, data: item }); } catch (error) { next(error); } },
    async update(req, res, next) { try { const data = schema.parse(req.body); if (!data.slug) data.slug = createSlug(data.title); const item = await Model.findByIdAndUpdate(req.params.id, data, { new: true, runValidators: true }); if (!item) return res.status(404).json({ success: false, message: 'Content not found.' }); res.json({ success: true, data: item }); } catch (error) { next(error); } },
    async remove(req, res, next) { try { const item = await Model.findByIdAndDelete(req.params.id); if (!item) return res.status(404).json({ success: false, message: 'Content not found.' }); res.json({ success: true, message: 'Deleted successfully.' }); } catch (error) { next(error); } }
  };
}
export const services = resourceController(Service, serviceSchema, 'title'); export const projects = resourceController(Project, projectSchema, '-date');
export async function statistics(req, res, next) { try { const data = await Statistic.find().sort('order'); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function saveStatistics(req, res, next) { try { if (!Array.isArray(req.body)) return res.status(400).json({ success: false, message: 'Statistics must be a list.' }); await Statistic.deleteMany({}); const data = await Statistic.insertMany(req.body.map((item, order) => ({ value: String(item.value || '').slice(0, 30), label: String(item.label || '').slice(0, 80), icon: String(item.icon || 'Heart').slice(0, 40), order }))); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function getPage(req, res, next) { try { const data = await Page.findOne({ key: req.params.key }); res.json({ success: true, data: data || { key: req.params.key, content: {} } }); } catch (error) { next(error); } }
export async function savePage(req, res, next) { try { const data = await Page.findOneAndUpdate({ key: req.params.key }, { content: req.body.content }, { upsert: true, new: true, runValidators: true }); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function getSettings(req, res, next) { try { const data = await SiteSetting.findOne(); res.json({ success: true, data: data || {} }); } catch (error) { next(error); } }
export async function saveSettings(req, res, next) { try { const fields = ['organizationName','logoUrl','email','phone','address','facebook','instagram','twitter','linkedin','footerText']; const clean = Object.fromEntries(fields.map((field) => [field, typeof req.body[field] === 'string' ? req.body[field].trim() : ''])); const data = await SiteSetting.findOneAndUpdate({}, clean, { upsert: true, new: true }); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function submitContact(req, res, next) { try { const data = contactSchema.parse(req.body); await ContactMessage.create(data); res.status(201).json({ success: true, message: 'Thank you. Your message has been sent.' }); } catch (error) { next(error); } }
export async function messages(req, res, next) { try { const data = await ContactMessage.find().sort('-createdAt'); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function markMessage(req, res, next) { try { const data = await ContactMessage.findByIdAndUpdate(req.params.id, { isRead: Boolean(req.body.isRead) }, { new: true }); if (!data) return res.status(404).json({ success: false, message: 'Message not found.' }); res.json({ success: true, data }); } catch (error) { next(error); } }
export async function deleteMessage(req, res, next) { try { const data = await ContactMessage.findByIdAndDelete(req.params.id); if (!data) return res.status(404).json({ success: false, message: 'Message not found.' }); res.json({ success: true, message: 'Deleted successfully.' }); } catch (error) { next(error); } }
export async function dashboard(req, res, next) { try { const [totalServices, publishedServices, totalProjects, publishedProjects, totalMessages, unreadMessages, recentMessages, recentProjects] = await Promise.all([Service.countDocuments(), Service.countDocuments({ status: 'published' }), Project.countDocuments(), Project.countDocuments({ status: 'published' }), ContactMessage.countDocuments(), ContactMessage.countDocuments({ isRead: false }), ContactMessage.find().sort('-createdAt').limit(5), Project.find().sort('-createdAt').limit(5)]); res.json({ success: true, data: { totalServices, publishedServices, totalProjects, publishedProjects, totalMessages, unreadMessages, recentMessages, recentProjects } }); } catch (error) { next(error); } }
