import { ArrowRight, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';

export function ServiceCard({ item }) {
  return <article className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_45px_rgba(15,23,42,.16)]"><Link className="relative block h-52 overflow-hidden" to={`/services/${item.slug}`} aria-label={`View ${item.title}`}><img className="h-full w-full object-cover transition duration-700 ease-out group-hover:scale-110" src={item.imageUrl || 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=900&q=80'} alt=""/><span className="absolute inset-0 bg-gradient-to-t from-[#000f22]/70 via-[#000f22]/10 to-transparent opacity-0 transition duration-300 group-hover:opacity-100"/><span className="absolute bottom-5 left-5 inline-flex translate-y-3 items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold text-[#000f22] opacity-0 shadow-lg transition duration-300 group-hover:translate-y-0 group-hover:opacity-100">View service <ArrowRight size={15}/></span></Link><div className="flex min-h-60 flex-col p-6"><span className="w-max rounded-full bg-[#e7f5e5] px-3 py-1 text-xs font-bold text-green">Program</span><h3 className="mt-4 text-xl font-bold text-[#000f22]">{item.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[#43474d]">{item.shortDescription}</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-green transition-all hover:gap-3 hover:text-[#1b6d24]" to={`/services/${item.slug}`}>Learn more <ArrowRight size={16}/></Link></div></article>;
}

export function ProjectCard({ item }) {
  return <article className="flex flex-col gap-5 rounded-xl border border-[#c4c6ce] bg-white p-4 shadow-[0_4px_20px_rgba(15,23,42,.08)] sm:flex-row"><img className="h-44 w-full rounded-lg object-cover sm:w-2/5" src={item.imageUrl || 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=900&q=80'} alt=""/><div className="flex-1"><p className="text-xs font-bold text-green">{new Date(item.date).toLocaleDateString()}</p><h3 className="mt-2 text-xl font-bold text-[#000f22]">{item.title}</h3><p className="mt-2 flex items-center gap-1 text-xs text-[#43474d]"><MapPin size={14}/>{item.location}</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#000f22] underline" to={`/projects/${item.slug}`}>Read report <ArrowRight size={16}/></Link></div></article>;
}
